import { Bell, CheckCircle2, ChevronRight, Heart, Users, Activity, Star } from "lucide-react";
import { Link } from "react-router-dom";
import { features, steps, roleCards, testimonials } from "./landingData";

function SectionHeading({ title, description }) { return <div className="max-w-xl mb-14"><h2 className="text-4xl text-gray-900 mb-3" style={{ fontFamily: "var(--font-heading)" }}>{title}</h2>{description && <p className="text-gray-500 text-lg">{description}</p>}</div>; }

export function LandingStats() {
  const stats = [["1,200+", "Registered Donors", Users], ["< 60s", "Alert Speed", Bell], ["4", "DSA Algorithms", Activity], ["93%", "Requests Fulfilled", Heart]];
  return <section className="bg-red-600 py-14"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-2 lg:grid-cols-4 gap-8 text-center">{stats.map(([value, label, Icon]) => <div key={label}><Icon size={24} className="text-red-300 mx-auto mb-2" /><div className="font-mono text-3xl font-bold text-white" style={{ fontFamily: "var(--font-code)" }}>{value}</div><div className="text-red-200 text-sm mt-1">{label}</div></div>)}</div></div></section>;
}

export function FeaturesSection() { return <section id="features" className="py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><SectionHeading title="Six tools. One network." description="Each one cuts a specific friction point between a donor and a patient." /><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{features.map(([Icon, title, color, description]) => <div key={title} className="border border-gray-100 rounded-2xl p-6 hover:border-red-100 hover:shadow-lg hover:shadow-red-50/60 transition-all"><div className={`w-10 h-10 rounded-xl flex items-center justify-center mb-4 ${color}`}><Icon size={20} /></div><h3 className="font-semibold text-gray-900 mb-2 text-[15px]">{title}</h3><p className="text-sm text-gray-500 leading-relaxed">{description}</p></div>)}</div></div></section>; }

export function HowItWorksSection() { return <section id="how-it-works" className="py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><SectionHeading title="Four steps. No phone calls." description="The whole process runs through the platform." /><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">{steps.map(([number, title, description], index) => <div key={number} className="relative">{index < steps.length - 1 && <div className="hidden lg:block absolute top-7 left-full w-full h-px bg-gradient-to-r from-red-200 to-transparent z-0" />}<div className="relative z-10"><div className="font-mono text-5xl font-bold text-red-100 mb-4 leading-none" style={{ fontFamily: "var(--font-code)" }}>{number}</div><h3 className="font-semibold text-gray-900 mb-2 text-[15px]">{title}</h3><p className="text-sm text-gray-500 leading-relaxed">{description}</p></div></div>)}</div><Link to="/register/donor" className="inline-flex items-center gap-2 bg-red-600 text-white font-semibold px-7 py-3.5 rounded-xl hover:bg-red-700 transition-all shadow-lg shadow-red-100 no-underline mt-14">Create your account <ChevronRight size={16} /></Link></div></section>; }

export function RoleCardsSection() { return <section className="py-24 bg-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><SectionHeading title="Pick your role" description="Each role gets a dashboard built around what that person does." /><div className="grid md:grid-cols-3 gap-6">{roleCards.map((card) => <div key={card.title} className="border border-gray-100 rounded-2xl overflow-hidden hover:shadow-xl transition-all"><div className={`${card.color} p-8 flex items-center justify-between`}><h3 className="text-2xl font-bold text-white">{card.title}</h3><img src={card.image} alt="" aria-hidden="true" className="w-12 h-12" /></div><div className="p-6"><ul className="space-y-2.5 mb-6">{card.items.map((item) => <li key={item} className="flex items-center gap-2.5 text-sm text-gray-600"><CheckCircle2 size={14} className="text-green-500 shrink-0" />{item}</li>)}</ul><Link to={card.href} className="block w-full border-2 border-gray-200 text-sm font-semibold py-2.5 rounded-xl hover:border-red-200 hover:text-red-700 transition-all text-center no-underline text-gray-800">Join as {card.title}</Link></div></div>)}</div></div></section>; }

export function TestimonialsSection() { return <section className="py-24 bg-gray-50"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><SectionHeading title="From donors and patients" /><div className="grid md:grid-cols-3 gap-6">{testimonials.map(([name, role, avatar, text]) => <div key={name} className="bg-white border border-gray-100 rounded-2xl p-6 shadow-sm"><div className="flex gap-1 mb-4">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={13} className="text-amber-400 fill-amber-400" />)}</div><p className="text-gray-700 text-sm leading-relaxed mb-6">"{text}"</p><div className="flex items-center gap-3"><div className="w-9 h-9 bg-red-100 rounded-full flex items-center justify-center text-xs font-bold text-red-700">{avatar}</div><div><div className="text-sm font-semibold text-gray-900">{name}</div><div className="text-xs text-gray-400">{role}</div></div></div></div>)}</div></div></section>; }
